### ISSUE TITLE
Using stream causing a code: "ECONNRESET"

### ISSUE THREAD

**Issue by krohm** [timoklimmer/powerproxy-aoai#65]
When using stream:true we get 
![image](https://github.com/timoklimmer/powerproxy-aoai/assets/8727697/af03f82c-bd15-49ee-8df2-68a59b6c0f92)

**Comment by timoklimmer** [comment]
Hi @krohm, are you using the latest version? I remember there was an issue in an earlier version which has been fixed meanwhile. I also checked your example against the latest version and did not encounter any issues. You might also want to check your config and for example make sure that the deployment used in your script actually exists. Unfortunately, due to the streaming protocol, we cannot provide more details in the streaming result, but if you look at the console output of PowerProxy, you will see a more detailed exception.

**Comment by krohm** [comment]
hi @timoklimmer , thanks for the hint. Indeed, it was a not configured Log Analytics Section in the config.
