### ISSUE TITLE
Feature Request: Explicitly log model, model version and API version

### ISSUE THREAD

**Issue by krohm** [timoklimmer/powerproxy-aoai#92]
Hi, not an issue, but a feature request:
Is it possible to log additionally to the Calls the Model, Model Version and API-Version that was used by the call?

**Comment by timoklimmer** [comment]
Hi @krohm, I have added the API version to the logs and released a new version. Logging the model and model version is a bit more involved, hence won't implement for now. If you need the model and model version, I suggest to name your deployments accordingly. Since requests will use the virtual deployment name, applications won't need to be changed with new model/versions. Alternatively, you can lookup the model/version in the details of the respective deployments.
